# Create a program that will play the “cows and bulls” game with the user. The game works like this:
#
# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number.
# For every digit that the user guessed correctly in the correct place, they have a “cow”.
# For every digit the user guessed correctly in the wrong place is a “bull.”
# Every time the user makes a guess, tell them how many “cows” and “bulls” they have.
# Once the user guesses the correct number, the game is over.
# Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.
#
# Say the number generated by the computer is 1038. An example interaction could look like this:
#
# Welcome to the Cows and Bulls Game!
# Enter a number:
# >>> 1234
# 2 cows, 0 bulls
# >>> 1256
# 1 cow, 1 bull
# ...
# Until the user guesses the number.

import random


def losuj_liczbe():
    liczba = []
    for i in range(4):
        nowa = random.randint(0, 9)
        liczba.append(nowa)
    return liczba


def porownaj(liczba, odpowiedz):
    cow = 0
    bull = 0
    for i in range(4):
        #print("Liczba: {} , Odpowiedz: {}".format(liczba[i], odpowiedz[i]))
        if liczba[i] == odpowiedz[i]:
            cow += 1
        else:
            if odpowiedz[i] in liczba:
                bull += 1
    print("Cows: {} , Bulls: {}".format(cow, bull))
    return cow, bull


if __name__ == "__main__":
    zagadka = losuj_liczbe()
    tura = 1
    while True:
        print("Tura nr {}".format(tura))
        odp = input("Podaj liczbe:")
        odp_list = list(odp)
        odp_list = [int(i) for i in odp_list]
        cows, bulls = porownaj(zagadka, odp_list)
        if cows == 4:
            break
        tura += 1
    print( " KONIEC GRY - ZGADLES!!!")